"""Added sequence schema

Revision ID: 151030d7d259
Revises: d1d66ae5d7c4
Create Date: 2026-01-12 15:53:46.041550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151030d7d259'
down_revision: Union[str, None] = 'd1d66ae5d7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letter_writing_sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('sequence_images', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['letter_writing_lectures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letter_writing_sequences_id'), 'letter_writing_sequences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_letter_writing_sequences_id'), table_name='letter_writing_sequences')
    op.drop_table('letter_writing_sequences')
    # ### end Alembic commands ###
