"""Added dialects selection schema

Revision ID: 2527ca66d881
Revises: 6bd66655512e
Create Date: 2026-01-10 15:40:36.926894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2527ca66d881'
down_revision: Union[str, None] = '6bd66655512e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add DIALECT_SELECTION to the resourcetype enum
    op.execute("ALTER TYPE resourcetype ADD VALUE 'DIALECT_SELECTION'")
    
    op.create_table('dialect_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialect_selection_dialects',
    sa.Column('dialect_selection_id', sa.Integer(), nullable=False),
    sa.Column('dialect_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dialect_id'], ['dialects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dialect_selection_id'], ['dialect_selections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dialect_selection_id', 'dialect_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialect_selection_dialects')
    op.drop_table('dialect_selections')
    # Note: PostgreSQL does not support removing enum values directly.
    # DIALECT_SELECTION will remain in resourcetype enum after downgrade.
    # ### end Alembic commands ###
