"""Added dialect fields on Course and UserCourseProgress

Revision ID: 33935f5fcb40
Revises: g8h9i0j1k2l3
Create Date: 2026-01-15 21:07:44.282240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33935f5fcb40'
down_revision: Union[str, None] = 'g8h9i0j1k2l3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('default_dialect', sa.Enum('MSA', 'LEVANTINE', 'EGYPTIAN', name='availabledialect'), nullable=True))
    op.add_column('user_course_progress', sa.Column('default_dialect', sa.Enum('MSA', 'LEVANTINE', 'EGYPTIAN', name='availabledialect'), nullable=True))
    
    # Drop constraints and index that previously included dialect column
    op.drop_constraint('uq_user_course_dialect', 'user_course_progress', type_='unique')
    op.drop_index('idx_user_course_dialect', table_name='user_course_progress')
    
    # Drop and recreate dialect column since table is empty and we're changing type
    op.drop_column('user_course_progress', 'dialect')
    op.add_column('user_course_progress', sa.Column('dialect', sa.Enum('MSA', 'LEVANTINE', 'EGYPTIAN', name='availabledialect'), nullable=True))
    
    # Recreate constraints and index WITHOUT dialect (only user_id and course_name)
    op.create_unique_constraint('uq_user_course_dialect', 'user_course_progress', ['user_id', 'course_name'])
    op.create_index('idx_user_course_dialect', 'user_course_progress', ['user_id', 'course_name'])
    
    op.add_column('users', sa.Column('courses_completed', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'courses_completed')
    
    # Drop constraints and index (without dialect)
    op.drop_index('idx_user_course_dialect', table_name='user_course_progress')
    op.drop_constraint('uq_user_course_dialect', 'user_course_progress', type_='unique')
    
    # Drop and recreate dialect column back to VARCHAR
    op.drop_column('user_course_progress', 'dialect')
    op.add_column('user_course_progress', sa.Column('dialect', sa.VARCHAR(), nullable=True))
    
    # Recreate constraints and index WITH VARCHAR dialect (old structure)
    op.create_unique_constraint('uq_user_course_dialect', 'user_course_progress', ['user_id', 'course_name', 'dialect'])
    op.create_index('idx_user_course_dialect', 'user_course_progress', ['user_id', 'course_name', 'dialect'])
    
    op.drop_column('user_course_progress', 'default_dialect')
    op.drop_column('courses', 'default_dialect')
    # ### end Alembic commands ###
