"""Added content field to letter writing lecture with server default

Revision ID: 45746cc6bbe0
Revises: 5fda38a8681d
Create Date: 2026-02-03 23:49:23.313807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45746cc6bbe0'
down_revision: Union[str, None] = '5fda38a8681d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letter_writing_lectures', sa.Column('content', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('letter_writing_lectures', 'content')
    # ### end Alembic commands ###
