"""Add bidirectional relationships and letter writing sequences

Revision ID: 45ea400519ca
Revises: b1f25d51a1eb
Create Date: 2026-01-12 17:10:13.673105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45ea400519ca'
down_revision: Union[str, None] = 'b1f25d51a1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letter_writing_problems', sa.Column('letter', sa.String(), nullable=False))
    op.drop_column('letter_writing_problems', 'word')
    op.drop_column('letter_writing_problems', 'writing_sequence')
    op.add_column('letter_writing_sequences', sa.Column('problem_id', sa.Integer(), nullable=True))
    op.alter_column('letter_writing_sequences', 'lecture_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'letter_writing_sequences', 'letter_writing_problems', ['problem_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'letter_writing_sequences', type_='foreignkey')
    op.alter_column('letter_writing_sequences', 'lecture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('letter_writing_sequences', 'problem_id')
    op.add_column('letter_writing_problems', sa.Column('writing_sequence', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('letter_writing_problems', sa.Column('word', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('letter_writing_problems', 'letter')
    # ### end Alembic commands ###
