"""Initial schema

Revision ID: 53960b0924b6
Revises: 
Create Date: 2026-01-08 22:42:02.588914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53960b0924b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_type', sa.Enum('LETTER_SPEAKING_LECTURE', 'LETTER_WRITING_LECTURE', 'VOCAB_LECTURE', 'INFO_LECTURE', 'READING_COMPREHENSION_TEXT', 'VOCAB_WORD', 'LETTER_PRONOUNCIATION_PROBLEM', 'WORD_PRONOUNCIATION_PROBLEM_SET', 'DISCRIMINATION_PROBLEM_SET', 'LETTER_RECOGNITION_PROBLEM_SET', 'LETTER_WRITING_PROBLEM_SET', 'LETTER_JOINING_PROBLEM_SET', 'DICTATION_PROBLEM_SET', 'VOCAB_READING_PROBLEM_SET', 'VOCAB_LISTENING_PROBLEM_SET', 'VOCAB_SPEAKING_PROBLEM_SET', 'READING_COMPREHENSION_MCQ_PROBLEM_SET', 'READING_COMPREHENSION_WRITING_PROBLEM_SET', 'UNIT_TEST', 'FINAL_EXAM', name='resourcetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('languages_learning', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dictation_problem_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discrimination_problem_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info_lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter_joining_problem_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter_pronounciation_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('letter', sa.String(), nullable=False),
    sa.Column('letter_audio', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter_recognition_problem_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter_speaking_lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(), nullable=False),
    sa.Column('content', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('letter_audio', sa.String(), nullable=False),
    sa.Column('word_audios', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter_writing_lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.String(), nullable=False),
    sa.Column('content', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('letter_writing_sequence', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter_writing_problem_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course', sa.Enum('BEGINNER_ARABIC', 'INTERMEDIATE_ARABIC', 'ADVANCED_ARABIC', name='course'), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course', 'unit', 'section', 'number', name='uq_course_unit_section_number')
    )
    op.create_index('idx_course_unit_section_number', 'modules', ['course', 'unit', 'section', 'number'], unique=False)
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('reading_comprehension_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_title', sa.String(), nullable=False),
    sa.Column('text', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_course_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.Enum('BEGINNER_ARABIC', 'INTERMEDIATE_ARABIC', 'ADVANCED_ARABIC', name='course'), nullable=False),
    sa.Column('dialect', sa.String(), nullable=True),
    sa.Column('curr_module', sa.Integer(), nullable=False),
    sa.Column('covered_words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('problem_counter', sa.Integer(), nullable=False),
    sa.Column('current_vocab_problem_set', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_name', 'dialect', name='uq_user_course_dialect')
    )
    op.create_index('idx_user_course_dialect', 'user_course_progress', ['user_id', 'course_name', 'dialect'], unique=False)
    op.create_index(op.f('ix_user_course_progress_id'), 'user_course_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_course_progress_user_id'), 'user_course_progress', ['user_id'], unique=False)
    op.create_table('vocab_lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_listening_problem_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('set_limit', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_reading_problem_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('set_limit', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_speaking_problem_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_pronounciation_problem_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dictation_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_set_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('word_audio', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_set_id'], ['dictation_problem_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discrimination_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_set_id', sa.Integer(), nullable=False),
    sa.Column('word_audio', sa.String(), nullable=False),
    sa.Column('incorrect_word_audio', sa.String(), nullable=False),
    sa.Column('answer_choices', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_set_id'], ['discrimination_problem_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter_joining_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_set_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('letter_list', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['problem_set_id'], ['letter_joining_problem_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter_recognition_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_set_id', sa.Integer(), nullable=False),
    sa.Column('partial_word', sa.String(), nullable=False),
    sa.Column('answer_choices', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_set_id'], ['letter_recognition_problem_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('letter_writing_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_set_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('reference_writing', sa.String(), nullable=False),
    sa.Column('writing_sequence', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['problem_set_id'], ['letter_writing_problem_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_comprehension_mcq_problem_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_id'], ['reading_comprehension_texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_comprehension_writing_problem_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_id'], ['reading_comprehension_texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_speaking_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_set_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_set_id'], ['vocab_speaking_problem_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('meaning', sa.String(), nullable=False),
    sa.Column('course', sa.Enum('BEGINNER_ARABIC', 'INTERMEDIATE_ARABIC', 'ADVANCED_ARABIC', name='course'), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('dialect', sa.String(), nullable=True),
    sa.Column('vocab_audio', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['vocab_lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_words_id'), 'vocab_words', ['id'], unique=False)
    op.create_table('word_pronounciation_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_set_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('word_audio', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_set_id'], ['word_pronounciation_problem_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_pronounciation_problems_id'), 'word_pronounciation_problems', ['id'], unique=False)
    op.create_table('reading_comprehension_mcq_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_set_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('question_audio', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('answer_choices', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['problem_set_id'], ['reading_comprehension_mcq_problem_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_comprehension_writing_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_set_id', sa.Integer(), nullable=False),
    sa.Column('question_audio', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['problem_set_id'], ['reading_comprehension_writing_problem_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_listening_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_set_id', sa.Integer(), nullable=False),
    sa.Column('vocab_word_id', sa.Integer(), nullable=False),
    sa.Column('answer_choices', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['problem_set_id'], ['vocab_listening_problem_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_word_id'], ['vocab_words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_reading_problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_set_id', sa.Integer(), nullable=False),
    sa.Column('vocab_word_id', sa.Integer(), nullable=False),
    sa.Column('answer_choices', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['problem_set_id'], ['vocab_reading_problem_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_word_id'], ['vocab_words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_speaking_problem_words',
    sa.Column('vocab_speaking_problem_id', sa.Integer(), nullable=False),
    sa.Column('vocab_word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vocab_speaking_problem_id'], ['vocab_speaking_problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_word_id'], ['vocab_words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vocab_speaking_problem_id', 'vocab_word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocab_speaking_problem_words')
    op.drop_table('vocab_reading_problems')
    op.drop_table('vocab_listening_problems')
    op.drop_table('reading_comprehension_writing_problems')
    op.drop_table('reading_comprehension_mcq_problems')
    op.drop_index(op.f('ix_word_pronounciation_problems_id'), table_name='word_pronounciation_problems')
    op.drop_table('word_pronounciation_problems')
    op.drop_index(op.f('ix_vocab_words_id'), table_name='vocab_words')
    op.drop_table('vocab_words')
    op.drop_table('vocab_speaking_problems')
    op.drop_table('reading_comprehension_writing_problem_sets')
    op.drop_table('reading_comprehension_mcq_problem_sets')
    op.drop_table('letter_writing_problems')
    op.drop_table('letter_recognition_problems')
    op.drop_table('letter_joining_problems')
    op.drop_table('discrimination_problems')
    op.drop_table('dictation_problems')
    op.drop_table('word_pronounciation_problem_sets')
    op.drop_table('vocab_speaking_problem_sets')
    op.drop_table('vocab_reading_problem_sets')
    op.drop_table('vocab_listening_problem_sets')
    op.drop_table('vocab_lectures')
    op.drop_index(op.f('ix_user_course_progress_user_id'), table_name='user_course_progress')
    op.drop_index(op.f('ix_user_course_progress_id'), table_name='user_course_progress')
    op.drop_index('idx_user_course_dialect', table_name='user_course_progress')
    op.drop_table('user_course_progress')
    op.drop_table('reading_comprehension_texts')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_index('idx_course_unit_section_number', table_name='modules')
    op.drop_table('modules')
    op.drop_table('letter_writing_problem_sets')
    op.drop_table('letter_writing_lectures')
    op.drop_table('letter_speaking_lectures')
    op.drop_table('letter_recognition_problem_sets')
    op.drop_table('letter_pronounciation_problems')
    op.drop_table('letter_joining_problem_sets')
    op.drop_table('info_lectures')
    op.drop_table('discrimination_problem_sets')
    op.drop_table('dictation_problem_sets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
