"""Added language field to userCourseProgress

Revision ID: 5fda38a8681d
Revises: 33935f5fcb40
Create Date: 2026-01-27 07:55:46.045010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fda38a8681d'
down_revision: Union[str, None] = '33935f5fcb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_course_progress', sa.Column('language', sa.Enum('ARABIC', 'SPANISH', 'FRENCH', name='availablelanguage'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_course_progress', 'language')
    # ### end Alembic commands ###
