"""Added current_course to User

Revision ID: 637362d9aadf
Revises: 2527ca66d881
Create Date: 2026-01-10 15:55:47.485239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637362d9aadf'
down_revision: Union[str, None] = '2527ca66d881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_course', sa.Enum('BEGINNER_ARABIC', 'INTERMEDIATE_ARABIC', 'ADVANCED_ARABIC', name='availablecourse'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_course')
    # ### end Alembic commands ###
