"""Added dialect field to module

Revision ID: 66e0651fbc6e
Revises: e2e6241c27bd
Create Date: 2026-01-15 15:16:13.814826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e0651fbc6e'
down_revision: Union[str, None] = 'e2e6241c27bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('dialect', sa.Enum('MSA', 'LEVANTINE', 'EGYPTIAN', name='availabledialect'), nullable=True))
    op.add_column('users', sa.Column('current_dialect', sa.Enum('MSA', 'LEVANTINE', 'EGYPTIAN', name='availabledialect'), nullable=True))
    op.add_column('users', sa.Column('languages_learned', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'languages_learned')
    op.drop_column('users', 'current_dialect')
    op.drop_column('modules', 'dialect')
    # ### end Alembic commands ###
