"""Added total modules to courses

Revision ID: 6bd66655512e
Revises: 83fa6cec659c
Create Date: 2026-01-10 14:40:27.472162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd66655512e'
down_revision: Union[str, None] = '83fa6cec659c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('total_modules', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'total_modules')
    # ### end Alembic commands ###
