"""Added ref_modules field to course and userCourseProgress

Revision ID: 7cbf2b3ee642
Revises: ea99b66f2132
Create Date: 2026-02-05 03:33:54.130177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbf2b3ee642'
down_revision: Union[str, None] = 'ea99b66f2132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('ref_modules', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.add_column('user_course_progress', sa.Column('ref_modules', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_course_progress', 'ref_modules')
    op.drop_column('courses', 'ref_modules')
    # ### end Alembic commands ###
