"""Implemented Problem Sets schemas for Vocab Reading and Listening

Revision ID: 83fa6cec659c
Revises: c99692f23324
Create Date: 2026-01-09 23:58:15.289228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83fa6cec659c'
down_revision: Union[str, None] = 'c99692f23324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_listening_problem_sets_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_reading_problem_sets_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vocab_listening_problem_sets', sa.Column('collection_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_vocab_listening_problem_sets_id'), 'vocab_listening_problem_sets', ['id'], unique=False)
    op.drop_constraint('vocab_listening_problem_sets_id_fkey', 'vocab_listening_problem_sets', type_='foreignkey')
    op.create_foreign_key(None, 'vocab_listening_problem_sets', 'vocab_listening_problem_sets_collection', ['collection_id'], ['id'], ondelete='CASCADE')
    op.drop_column('vocab_listening_problem_sets', 'set_limit')
    op.add_column('vocab_reading_problem_sets', sa.Column('collection_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_vocab_reading_problem_sets_id'), 'vocab_reading_problem_sets', ['id'], unique=False)
    op.drop_constraint('vocab_reading_problem_sets_id_fkey', 'vocab_reading_problem_sets', type_='foreignkey')
    op.create_foreign_key(None, 'vocab_reading_problem_sets', 'vocab_reading_problem_sets_collection', ['collection_id'], ['id'], ondelete='CASCADE')
    op.drop_column('vocab_reading_problem_sets', 'set_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocab_reading_problem_sets', sa.Column('set_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vocab_reading_problem_sets', type_='foreignkey')
    op.create_foreign_key('vocab_reading_problem_sets_id_fkey', 'vocab_reading_problem_sets', 'resources', ['id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_vocab_reading_problem_sets_id'), table_name='vocab_reading_problem_sets')
    op.drop_column('vocab_reading_problem_sets', 'collection_id')
    op.add_column('vocab_listening_problem_sets', sa.Column('set_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vocab_listening_problem_sets', type_='foreignkey')
    op.create_foreign_key('vocab_listening_problem_sets_id_fkey', 'vocab_listening_problem_sets', 'resources', ['id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_vocab_listening_problem_sets_id'), table_name='vocab_listening_problem_sets')
    op.drop_column('vocab_listening_problem_sets', 'collection_id')
    op.drop_table('vocab_reading_problem_sets_collection')
    op.drop_table('vocab_listening_problem_sets_collection')
    # ### end Alembic commands ###
