"""Added gender field to User and VocabSpeakingProblemSets

Revision ID: b21a0c4979bd
Revises: c3d4e5f6g7h8
Create Date: 2026-01-10 20:15:42.143962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21a0c4979bd'
down_revision: Union[str, None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the gender enum type in PostgreSQL first
    gender_enum = sa.Enum('MALE', 'FEMALE', name='gender')
    gender_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('vocab_speaking_problem_sets_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False))
    op.add_column('vocab_speaking_problem_sets', sa.Column('collection_id', sa.Integer(), nullable=False))
    op.add_column('vocab_speaking_problem_sets', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False))
    op.create_index(op.f('ix_vocab_speaking_problem_sets_id'), 'vocab_speaking_problem_sets', ['id'], unique=False)
    op.drop_constraint('vocab_speaking_problem_sets_id_fkey', 'vocab_speaking_problem_sets', type_='foreignkey')
    op.create_foreign_key(None, 'vocab_speaking_problem_sets', 'vocab_speaking_problem_sets_collection', ['collection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vocab_speaking_problem_sets', type_='foreignkey')
    op.create_foreign_key('vocab_speaking_problem_sets_id_fkey', 'vocab_speaking_problem_sets', 'resources', ['id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_vocab_speaking_problem_sets_id'), table_name='vocab_speaking_problem_sets')
    op.drop_column('vocab_speaking_problem_sets', 'gender')
    op.drop_column('vocab_speaking_problem_sets', 'collection_id')
    op.drop_column('users', 'gender')
    op.drop_table('vocab_speaking_problem_sets_collection')
    
    # Drop the gender enum type
    gender_enum = sa.Enum('MALE', 'FEMALE', name='gender')
    gender_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
