"""Added number field to VocabWord

Revision ID: c99692f23324
Revises: db113864dd58
Create Date: 2026-01-09 22:49:51.290932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99692f23324'
down_revision: Union[str, None] = 'db113864dd58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocab_words', sa.Column('number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocab_words', 'number')
    # ### end Alembic commands ###
