"""Used just word now in recognition

Revision ID: cc599f2b6a5a
Revises: e72c773396b7
Create Date: 2026-01-11 21:59:10.891062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc599f2b6a5a'
down_revision: Union[str, None] = 'e72c773396b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letter_recognition_problems', sa.Column('word', sa.String(), nullable=False))
    op.drop_column('letter_recognition_problems', 'partial_word')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letter_recognition_problems', sa.Column('partial_word', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('letter_recognition_problems', 'word')
    # ### end Alembic commands ###
