"""Fixed letter writing lecture table

Revision ID: d1d66ae5d7c4
Revises: cc599f2b6a5a
Create Date: 2026-01-12 15:47:10.304548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1d66ae5d7c4'
down_revision: Union[str, None] = 'cc599f2b6a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('letter_writing_lectures', 'letter_writing_sequence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('letter_writing_lectures', sa.Column('letter_writing_sequence', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
