"""Added total modules in UserProgressSchema

Revision ID: db113864dd58
Revises: 6c05bff0d1a9
Create Date: 2026-01-09 20:51:23.125070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db113864dd58'
down_revision: Union[str, None] = '6c05bff0d1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_course_progress', sa.Column('total_modules', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_course_progress', 'total_modules')
    # ### end Alembic commands ###
