"""Make curr_course in User nullable

Revision ID: e2e6241c27bd
Revises: 45ea400519ca
Create Date: 2026-01-13 14:05:49.714747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2e6241c27bd'
down_revision: Union[str, None] = '45ea400519ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'current_course',
               existing_type=postgresql.ENUM('BEGINNER_ARABIC', 'INTERMEDIATE_ARABIC', 'ADVANCED_ARABIC', name='availablecourse'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'current_course',
               existing_type=postgresql.ENUM('BEGINNER_ARABIC', 'INTERMEDIATE_ARABIC', 'ADVANCED_ARABIC', name='availablecourse'),
               nullable=False)
    # ### end Alembic commands ###
