"""Fix reading comprehension texts schema

Revision ID: e72c773396b7
Revises: 0eaacc21c131
Create Date: 2026-01-10 21:40:48.450935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72c773396b7'
down_revision: Union[str, None] = '0eaacc21c131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reading_comprehension_texts_id'), 'reading_comprehension_texts', ['id'], unique=False)
    op.drop_constraint('reading_comprehension_texts_id_fkey', 'reading_comprehension_texts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('reading_comprehension_texts_id_fkey', 'reading_comprehension_texts', 'resources', ['id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reading_comprehension_texts_id'), table_name='reading_comprehension_texts')
    # ### end Alembic commands ###
