"""Fixed vocab speaking

Revision ID: ea99b66f2132
Revises: 45746cc6bbe0
Create Date: 2026-02-04 16:08:34.265140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea99b66f2132'
down_revision: Union[str, None] = '45746cc6bbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocab_speaking_problem_sets', sa.Column('dialect', sa.Enum('MSA', 'LEVANTINE', 'EGYPTIAN', name='availabledialect'), nullable=True))
    op.alter_column('vocab_speaking_problem_sets', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='gender'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vocab_speaking_problem_sets', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='gender'),
               nullable=False)
    op.drop_column('vocab_speaking_problem_sets', 'dialect')
    # ### end Alembic commands ###
